import { Text, ScrollView } from 'react-native'

export default function BoardPage() {
  return (
    <ScrollView>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
      <Text>Board page</Text>
    </ScrollView>
  )
}
